### ISSUE TITLE
Java15 discrepancy with tapis-meta-vdj (v2)

### ISSUE THREAD

**Issue by jagaither** [tapis-project/tapis-shared-java#13]
Currently tapis-meta-vdj (v2) is using the tapis-shared v3 code for exceptions, messaging and more. This gives us two options: 

1. Move shared code being used by tapis-meta-vdj (v2)into its own directory of meta-vdj (v2) so it no longer inherits the current v3 shared code
2. Create a java15 jar of the shared code specifically for use with meta-vdj (v2) and future deployments

- [x] Determine which classes from v3 shared are being used by tapis-meta-vdj (v2)
- [x] preferably copy those classes into a directory in meta-vdj (v2) so they can directly be deployed and updated in tandem with meta-vdj  (v2)
- [x] deploy new poms and code in meta-vdj
